// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: network/network.proto

package network

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNetworkStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkStatsRequest) Reset() {
	*x = GetNetworkStatsRequest{}
	mi := &file_network_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkStatsRequest) ProtoMessage() {}

func (x *GetNetworkStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkStatsRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkStatsRequest) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{0}
}

func (x *GetNetworkStatsRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetNetworkStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*NetworkInterface    `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkStatsResponse) Reset() {
	*x = GetNetworkStatsResponse{}
	mi := &file_network_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkStatsResponse) ProtoMessage() {}

func (x *GetNetworkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkStatsResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkStatsResponse) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{1}
}

func (x *GetNetworkStatsResponse) GetInterfaces() []*NetworkInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *GetNetworkStatsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	RxBytes       float64                `protobuf:"fixed64,3,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       float64                `protobuf:"fixed64,4,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_network_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_network_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_network_network_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetworkInterface) GetRxBytes() float64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkInterface) GetTxBytes() float64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

var File_network_network_proto protoreflect.FileDescriptor

const file_network_network_proto_rawDesc = "" +
	"\n" +
	"\x15network/network.proto\x12\anetwork\x1a\x1cgoogle/api/annotations.proto\"4\n" +
	"\x16GetNetworkStatsRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"r\n" +
	"\x17GetNetworkStatsResponse\x129\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x19.network.NetworkInterfaceR\n" +
	"interfaces\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"l\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x19\n" +
	"\brx_bytes\x18\x03 \x01(\x01R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x04 \x01(\x01R\atxBytes2\x81\x01\n" +
	"\x0eNetworkService\x12o\n" +
	"\x0fGetNetworkStats\x12\x1f.network.GetNetworkStatsRequest\x1a .network.GetNetworkStatsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/network/statsB\x1fZ\x1dsmart-monitor/pbtypes/networkb\x06proto3"

var (
	file_network_network_proto_rawDescOnce sync.Once
	file_network_network_proto_rawDescData []byte
)

func file_network_network_proto_rawDescGZIP() []byte {
	file_network_network_proto_rawDescOnce.Do(func() {
		file_network_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_network_proto_rawDesc), len(file_network_network_proto_rawDesc)))
	})
	return file_network_network_proto_rawDescData
}

var file_network_network_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_network_network_proto_goTypes = []any{
	(*GetNetworkStatsRequest)(nil),  // 0: network.GetNetworkStatsRequest
	(*GetNetworkStatsResponse)(nil), // 1: network.GetNetworkStatsResponse
	(*NetworkInterface)(nil),        // 2: network.NetworkInterface
}
var file_network_network_proto_depIdxs = []int32{
	2, // 0: network.GetNetworkStatsResponse.interfaces:type_name -> network.NetworkInterface
	0, // 1: network.NetworkService.GetNetworkStats:input_type -> network.GetNetworkStatsRequest
	1, // 2: network.NetworkService.GetNetworkStats:output_type -> network.GetNetworkStatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_network_network_proto_init() }
func file_network_network_proto_init() {
	if File_network_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_network_proto_rawDesc), len(file_network_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_network_proto_goTypes,
		DependencyIndexes: file_network_network_proto_depIdxs,
		MessageInfos:      file_network_network_proto_msgTypes,
	}.Build()
	File_network_network_proto = out.File
	file_network_network_proto_goTypes = nil
	file_network_network_proto_depIdxs = nil
}
