// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: Infrastructure/storage/storage.proto

package storage

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageRequest) Reset() {
	*x = GetStorageRequest{}
	mi := &file_Infrastructure_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageRequest) ProtoMessage() {}

func (x *GetStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageRequest.ProtoReflect.Descriptor instead.
func (*GetStorageRequest) Descriptor() ([]byte, []int) {
	return file_Infrastructure_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GetStorageRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetStorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StorageItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageResponse) Reset() {
	*x = GetStorageResponse{}
	mi := &file_Infrastructure_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageResponse) ProtoMessage() {}

func (x *GetStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageResponse.ProtoReflect.Descriptor instead.
func (*GetStorageResponse) Descriptor() ([]byte, []int) {
	return file_Infrastructure_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetStorageResponse) GetItems() []*StorageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetStorageResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type StorageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capacity      float64                `protobuf:"fixed64,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Used          float64                `protobuf:"fixed64,4,opt,name=used,proto3" json:"used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageItem) Reset() {
	*x = StorageItem{}
	mi := &file_Infrastructure_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageItem) ProtoMessage() {}

func (x *StorageItem) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageItem.ProtoReflect.Descriptor instead.
func (*StorageItem) Descriptor() ([]byte, []int) {
	return file_Infrastructure_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StorageItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StorageItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StorageItem) GetCapacity() float64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StorageItem) GetUsed() float64 {
	if x != nil {
		return x.Used
	}
	return 0
}

var File_Infrastructure_storage_storage_proto protoreflect.FileDescriptor

const file_Infrastructure_storage_storage_proto_rawDesc = "" +
	"\n" +
	"$Infrastructure/storage/storage.proto\x12\astorage\x1a\x1cgoogle/api/annotations.proto\"/\n" +
	"\x11GetStorageRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"^\n" +
	"\x12GetStorageResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.storage.StorageItemR\x05items\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"a\n" +
	"\vStorageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x01R\bcapacity\x12\x12\n" +
	"\x04used\x18\x04 \x01(\x01R\x04used2l\n" +
	"\x0eStorageService\x12Z\n" +
	"\n" +
	"GetStorage\x12\x1a.storage.GetStorageRequest\x1a\x1b.storage.GetStorageResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/storageB.Z,smart-monitor/pbtypes/Infrastructure/storageb\x06proto3"

var (
	file_Infrastructure_storage_storage_proto_rawDescOnce sync.Once
	file_Infrastructure_storage_storage_proto_rawDescData []byte
)

func file_Infrastructure_storage_storage_proto_rawDescGZIP() []byte {
	file_Infrastructure_storage_storage_proto_rawDescOnce.Do(func() {
		file_Infrastructure_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Infrastructure_storage_storage_proto_rawDesc), len(file_Infrastructure_storage_storage_proto_rawDesc)))
	})
	return file_Infrastructure_storage_storage_proto_rawDescData
}

var file_Infrastructure_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Infrastructure_storage_storage_proto_goTypes = []any{
	(*GetStorageRequest)(nil),  // 0: storage.GetStorageRequest
	(*GetStorageResponse)(nil), // 1: storage.GetStorageResponse
	(*StorageItem)(nil),        // 2: storage.StorageItem
}
var file_Infrastructure_storage_storage_proto_depIdxs = []int32{
	2, // 0: storage.GetStorageResponse.items:type_name -> storage.StorageItem
	0, // 1: storage.StorageService.GetStorage:input_type -> storage.GetStorageRequest
	1, // 2: storage.StorageService.GetStorage:output_type -> storage.GetStorageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Infrastructure_storage_storage_proto_init() }
func file_Infrastructure_storage_storage_proto_init() {
	if File_Infrastructure_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Infrastructure_storage_storage_proto_rawDesc), len(file_Infrastructure_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Infrastructure_storage_storage_proto_goTypes,
		DependencyIndexes: file_Infrastructure_storage_storage_proto_depIdxs,
		MessageInfos:      file_Infrastructure_storage_storage_proto_msgTypes,
	}.Build()
	File_Infrastructure_storage_storage_proto = out.File
	file_Infrastructure_storage_storage_proto_goTypes = nil
	file_Infrastructure_storage_storage_proto_depIdxs = nil
}
