// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: Infrastructure/machines/machine.proto

package machines

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMachinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachinesRequest) Reset() {
	*x = GetMachinesRequest{}
	mi := &file_Infrastructure_machines_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachinesRequest) ProtoMessage() {}

func (x *GetMachinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_machines_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachinesRequest.ProtoReflect.Descriptor instead.
func (*GetMachinesRequest) Descriptor() ([]byte, []int) {
	return file_Infrastructure_machines_machine_proto_rawDescGZIP(), []int{0}
}

func (x *GetMachinesRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetMachinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machines      []*Machine             `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachinesResponse) Reset() {
	*x = GetMachinesResponse{}
	mi := &file_Infrastructure_machines_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachinesResponse) ProtoMessage() {}

func (x *GetMachinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_machines_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachinesResponse.ProtoReflect.Descriptor instead.
func (*GetMachinesResponse) Descriptor() ([]byte, []int) {
	return file_Infrastructure_machines_machine_proto_rawDescGZIP(), []int{1}
}

func (x *GetMachinesResponse) GetMachines() []*Machine {
	if x != nil {
		return x.Machines
	}
	return nil
}

func (x *GetMachinesResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Machine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_Infrastructure_machines_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_machines_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_Infrastructure_machines_machine_proto_rawDescGZIP(), []int{2}
}

func (x *Machine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Machine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Machine) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Machine) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

var File_Infrastructure_machines_machine_proto protoreflect.FileDescriptor

const file_Infrastructure_machines_machine_proto_rawDesc = "" +
	"\n" +
	"%Infrastructure/machines/machine.proto\x12\bmachines\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\x12GetMachinesRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"b\n" +
	"\x13GetMachinesResponse\x12-\n" +
	"\bmachines\x18\x01 \x03(\v2\x11.machines.MachineR\bmachines\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"]\n" +
	"\aMachine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation2r\n" +
	"\x0eMachineService\x12`\n" +
	"\vGetMachines\x12\x1c.machines.GetMachinesRequest\x1a\x1d.machines.GetMachinesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/machinesB/Z-smart-monitor/pbtypes/Infrastructure/machinesb\x06proto3"

var (
	file_Infrastructure_machines_machine_proto_rawDescOnce sync.Once
	file_Infrastructure_machines_machine_proto_rawDescData []byte
)

func file_Infrastructure_machines_machine_proto_rawDescGZIP() []byte {
	file_Infrastructure_machines_machine_proto_rawDescOnce.Do(func() {
		file_Infrastructure_machines_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Infrastructure_machines_machine_proto_rawDesc), len(file_Infrastructure_machines_machine_proto_rawDesc)))
	})
	return file_Infrastructure_machines_machine_proto_rawDescData
}

var file_Infrastructure_machines_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Infrastructure_machines_machine_proto_goTypes = []any{
	(*GetMachinesRequest)(nil),  // 0: machines.GetMachinesRequest
	(*GetMachinesResponse)(nil), // 1: machines.GetMachinesResponse
	(*Machine)(nil),             // 2: machines.Machine
}
var file_Infrastructure_machines_machine_proto_depIdxs = []int32{
	2, // 0: machines.GetMachinesResponse.machines:type_name -> machines.Machine
	0, // 1: machines.MachineService.GetMachines:input_type -> machines.GetMachinesRequest
	1, // 2: machines.MachineService.GetMachines:output_type -> machines.GetMachinesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Infrastructure_machines_machine_proto_init() }
func file_Infrastructure_machines_machine_proto_init() {
	if File_Infrastructure_machines_machine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Infrastructure_machines_machine_proto_rawDesc), len(file_Infrastructure_machines_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Infrastructure_machines_machine_proto_goTypes,
		DependencyIndexes: file_Infrastructure_machines_machine_proto_depIdxs,
		MessageInfos:      file_Infrastructure_machines_machine_proto_msgTypes,
	}.Build()
	File_Infrastructure_machines_machine_proto = out.File
	file_Infrastructure_machines_machine_proto_goTypes = nil
	file_Infrastructure_machines_machine_proto_depIdxs = nil
}
