// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: process/process.proto

package process

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProcessesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessesRequest) Reset() {
	*x = GetProcessesRequest{}
	mi := &file_process_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessesRequest) ProtoMessage() {}

func (x *GetProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessesRequest.ProtoReflect.Descriptor instead.
func (*GetProcessesRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{0}
}

func (x *GetProcessesRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*Process             `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessesResponse) Reset() {
	*x = GetProcessesResponse{}
	mi := &file_process_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessesResponse) ProtoMessage() {}

func (x *GetProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessesResponse.ProtoReflect.Descriptor instead.
func (*GetProcessesResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{1}
}

func (x *GetProcessesResponse) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *GetProcessesResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           float64                `protobuf:"fixed64,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        float64                `protobuf:"fixed64,4,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_process_process_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{2}
}

func (x *Process) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Process) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Process) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Process) GetMemory() float64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type KillProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessRequest) Reset() {
	*x = KillProcessRequest{}
	mi := &file_process_process_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessRequest) ProtoMessage() {}

func (x *KillProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessRequest.ProtoReflect.Descriptor instead.
func (*KillProcessRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{3}
}

func (x *KillProcessRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *KillProcessRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type KillProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessResponse) Reset() {
	*x = KillProcessResponse{}
	mi := &file_process_process_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessResponse) ProtoMessage() {}

func (x *KillProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessResponse.ProtoReflect.Descriptor instead.
func (*KillProcessResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{4}
}

func (x *KillProcessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *KillProcessResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_process_process_proto protoreflect.FileDescriptor

const file_process_process_proto_rawDesc = "" +
	"\n" +
	"\x15process/process.proto\x12\aprocess\x1a\x1cgoogle/api/annotations.proto\"1\n" +
	"\x13GetProcessesRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"d\n" +
	"\x14GetProcessesResponse\x12.\n" +
	"\tprocesses\x18\x01 \x03(\v2\x10.process.ProcessR\tprocesses\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"Y\n" +
	"\aProcess\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x01R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x01R\x06memory\"B\n" +
	"\x12KillProcessRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\"M\n" +
	"\x13KillProcessResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\xdd\x01\n" +
	"\x0eProcessService\x12b\n" +
	"\fGetProcesses\x12\x1c.process.GetProcessesRequest\x1a\x1d.process.GetProcessesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/processes\x12g\n" +
	"\vKillProcess\x12\x1b.process.KillProcessRequest\x1a\x1c.process.KillProcessResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/processes/killB\x1fZ\x1dsmart-monitor/pbtypes/processb\x06proto3"

var (
	file_process_process_proto_rawDescOnce sync.Once
	file_process_process_proto_rawDescData []byte
)

func file_process_process_proto_rawDescGZIP() []byte {
	file_process_process_proto_rawDescOnce.Do(func() {
		file_process_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_process_process_proto_rawDesc), len(file_process_process_proto_rawDesc)))
	})
	return file_process_process_proto_rawDescData
}

var file_process_process_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_process_process_proto_goTypes = []any{
	(*GetProcessesRequest)(nil),  // 0: process.GetProcessesRequest
	(*GetProcessesResponse)(nil), // 1: process.GetProcessesResponse
	(*Process)(nil),              // 2: process.Process
	(*KillProcessRequest)(nil),   // 3: process.KillProcessRequest
	(*KillProcessResponse)(nil),  // 4: process.KillProcessResponse
}
var file_process_process_proto_depIdxs = []int32{
	2, // 0: process.GetProcessesResponse.processes:type_name -> process.Process
	0, // 1: process.ProcessService.GetProcesses:input_type -> process.GetProcessesRequest
	3, // 2: process.ProcessService.KillProcess:input_type -> process.KillProcessRequest
	1, // 3: process.ProcessService.GetProcesses:output_type -> process.GetProcessesResponse
	4, // 4: process.ProcessService.KillProcess:output_type -> process.KillProcessResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_process_process_proto_init() }
func file_process_process_proto_init() {
	if File_process_process_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_process_process_proto_rawDesc), len(file_process_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_process_process_proto_goTypes,
		DependencyIndexes: file_process_process_proto_depIdxs,
		MessageInfos:      file_process_process_proto_msgTypes,
	}.Build()
	File_process_process_proto = out.File
	file_process_process_proto_goTypes = nil
	file_process_process_proto_depIdxs = nil
}
