// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: Infrastructure/servers/server.proto

package servers

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServersRequest) Reset() {
	*x = GetServersRequest{}
	mi := &file_Infrastructure_servers_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServersRequest) ProtoMessage() {}

func (x *GetServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_servers_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServersRequest.ProtoReflect.Descriptor instead.
func (*GetServersRequest) Descriptor() ([]byte, []int) {
	return file_Infrastructure_servers_server_proto_rawDescGZIP(), []int{0}
}

func (x *GetServersRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServersResponse) Reset() {
	*x = GetServersResponse{}
	mi := &file_Infrastructure_servers_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServersResponse) ProtoMessage() {}

func (x *GetServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_servers_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServersResponse.ProtoReflect.Descriptor instead.
func (*GetServersResponse) Descriptor() ([]byte, []int) {
	return file_Infrastructure_servers_server_proto_rawDescGZIP(), []int{1}
}

func (x *GetServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *GetServersResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_Infrastructure_servers_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_servers_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_Infrastructure_servers_server_proto_rawDescGZIP(), []int{2}
}

func (x *Server) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Server) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_Infrastructure_servers_server_proto protoreflect.FileDescriptor

const file_Infrastructure_servers_server_proto_rawDesc = "" +
	"\n" +
	"#Infrastructure/servers/server.proto\x12\aservers\x1a\x1cgoogle/api/annotations.proto\"/\n" +
	"\x11GetServersRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"]\n" +
	"\x12GetServersResponse\x12)\n" +
	"\aservers\x18\x01 \x03(\v2\x0f.servers.ServerR\aservers\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"D\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2k\n" +
	"\rServerService\x12Z\n" +
	"\n" +
	"GetServers\x12\x1a.servers.GetServersRequest\x1a\x1b.servers.GetServersResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/serversB.Z,smart-monitor/pbtypes/Infrastructure/serversb\x06proto3"

var (
	file_Infrastructure_servers_server_proto_rawDescOnce sync.Once
	file_Infrastructure_servers_server_proto_rawDescData []byte
)

func file_Infrastructure_servers_server_proto_rawDescGZIP() []byte {
	file_Infrastructure_servers_server_proto_rawDescOnce.Do(func() {
		file_Infrastructure_servers_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Infrastructure_servers_server_proto_rawDesc), len(file_Infrastructure_servers_server_proto_rawDesc)))
	})
	return file_Infrastructure_servers_server_proto_rawDescData
}

var file_Infrastructure_servers_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Infrastructure_servers_server_proto_goTypes = []any{
	(*GetServersRequest)(nil),  // 0: servers.GetServersRequest
	(*GetServersResponse)(nil), // 1: servers.GetServersResponse
	(*Server)(nil),             // 2: servers.Server
}
var file_Infrastructure_servers_server_proto_depIdxs = []int32{
	2, // 0: servers.GetServersResponse.servers:type_name -> servers.Server
	0, // 1: servers.ServerService.GetServers:input_type -> servers.GetServersRequest
	1, // 2: servers.ServerService.GetServers:output_type -> servers.GetServersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Infrastructure_servers_server_proto_init() }
func file_Infrastructure_servers_server_proto_init() {
	if File_Infrastructure_servers_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Infrastructure_servers_server_proto_rawDesc), len(file_Infrastructure_servers_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Infrastructure_servers_server_proto_goTypes,
		DependencyIndexes: file_Infrastructure_servers_server_proto_depIdxs,
		MessageInfos:      file_Infrastructure_servers_server_proto_msgTypes,
	}.Build()
	File_Infrastructure_servers_server_proto = out.File
	file_Infrastructure_servers_server_proto_goTypes = nil
	file_Infrastructure_servers_server_proto_depIdxs = nil
}
