// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: Infrastructure/containers/container.proto

package containers

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainersRequest) Reset() {
	*x = GetContainersRequest{}
	mi := &file_Infrastructure_containers_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainersRequest) ProtoMessage() {}

func (x *GetContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_containers_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainersRequest.ProtoReflect.Descriptor instead.
func (*GetContainersRequest) Descriptor() ([]byte, []int) {
	return file_Infrastructure_containers_container_proto_rawDescGZIP(), []int{0}
}

func (x *GetContainersRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainersResponse) Reset() {
	*x = GetContainersResponse{}
	mi := &file_Infrastructure_containers_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainersResponse) ProtoMessage() {}

func (x *GetContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_containers_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainersResponse.ProtoReflect.Descriptor instead.
func (*GetContainersResponse) Descriptor() ([]byte, []int) {
	return file_Infrastructure_containers_container_proto_rawDescGZIP(), []int{1}
}

func (x *GetContainersResponse) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *GetContainersResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_Infrastructure_containers_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_containers_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_Infrastructure_containers_container_proto_rawDescGZIP(), []int{2}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_Infrastructure_containers_container_proto protoreflect.FileDescriptor

const file_Infrastructure_containers_container_proto_rawDesc = "" +
	"\n" +
	")Infrastructure/containers/container.proto\x12\n" +
	"containers\x1a\x1cgoogle/api/annotations.proto\"2\n" +
	"\x14GetContainersRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"l\n" +
	"\x15GetContainersResponse\x125\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x15.containers.ContainerR\n" +
	"containers\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"]\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\x80\x01\n" +
	"\x10ContainerService\x12l\n" +
	"\rGetContainers\x12 .containers.GetContainersRequest\x1a!.containers.GetContainersResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/containersB1Z/smart-monitor/pbtypes/Infrastructure/containersb\x06proto3"

var (
	file_Infrastructure_containers_container_proto_rawDescOnce sync.Once
	file_Infrastructure_containers_container_proto_rawDescData []byte
)

func file_Infrastructure_containers_container_proto_rawDescGZIP() []byte {
	file_Infrastructure_containers_container_proto_rawDescOnce.Do(func() {
		file_Infrastructure_containers_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Infrastructure_containers_container_proto_rawDesc), len(file_Infrastructure_containers_container_proto_rawDesc)))
	})
	return file_Infrastructure_containers_container_proto_rawDescData
}

var file_Infrastructure_containers_container_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Infrastructure_containers_container_proto_goTypes = []any{
	(*GetContainersRequest)(nil),  // 0: containers.GetContainersRequest
	(*GetContainersResponse)(nil), // 1: containers.GetContainersResponse
	(*Container)(nil),             // 2: containers.Container
}
var file_Infrastructure_containers_container_proto_depIdxs = []int32{
	2, // 0: containers.GetContainersResponse.containers:type_name -> containers.Container
	0, // 1: containers.ContainerService.GetContainers:input_type -> containers.GetContainersRequest
	1, // 2: containers.ContainerService.GetContainers:output_type -> containers.GetContainersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Infrastructure_containers_container_proto_init() }
func file_Infrastructure_containers_container_proto_init() {
	if File_Infrastructure_containers_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Infrastructure_containers_container_proto_rawDesc), len(file_Infrastructure_containers_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Infrastructure_containers_container_proto_goTypes,
		DependencyIndexes: file_Infrastructure_containers_container_proto_depIdxs,
		MessageInfos:      file_Infrastructure_containers_container_proto_msgTypes,
	}.Build()
	File_Infrastructure_containers_container_proto = out.File
	file_Infrastructure_containers_container_proto_goTypes = nil
	file_Infrastructure_containers_container_proto_depIdxs = nil
}
