// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: device/screen.proto

package device

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetScreenCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScreenCaptureRequest) Reset() {
	*x = GetScreenCaptureRequest{}
	mi := &file_device_screen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScreenCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreenCaptureRequest) ProtoMessage() {}

func (x *GetScreenCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_screen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreenCaptureRequest.ProtoReflect.Descriptor instead.
func (*GetScreenCaptureRequest) Descriptor() ([]byte, []int) {
	return file_device_screen_proto_rawDescGZIP(), []int{0}
}

func (x *GetScreenCaptureRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetScreenCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScreenCaptureResponse) Reset() {
	*x = GetScreenCaptureResponse{}
	mi := &file_device_screen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScreenCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreenCaptureResponse) ProtoMessage() {}

func (x *GetScreenCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_screen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreenCaptureResponse.ProtoReflect.Descriptor instead.
func (*GetScreenCaptureResponse) Descriptor() ([]byte, []int) {
	return file_device_screen_proto_rawDescGZIP(), []int{1}
}

func (x *GetScreenCaptureResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *GetScreenCaptureResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetScreenCaptureResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SetScreenResolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetScreenResolutionRequest) Reset() {
	*x = SetScreenResolutionRequest{}
	mi := &file_device_screen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetScreenResolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetScreenResolutionRequest) ProtoMessage() {}

func (x *SetScreenResolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_screen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetScreenResolutionRequest.ProtoReflect.Descriptor instead.
func (*SetScreenResolutionRequest) Descriptor() ([]byte, []int) {
	return file_device_screen_proto_rawDescGZIP(), []int{2}
}

func (x *SetScreenResolutionRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SetScreenResolutionRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SetScreenResolutionRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type SetScreenResolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetScreenResolutionResponse) Reset() {
	*x = SetScreenResolutionResponse{}
	mi := &file_device_screen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetScreenResolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetScreenResolutionResponse) ProtoMessage() {}

func (x *SetScreenResolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_screen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetScreenResolutionResponse.ProtoReflect.Descriptor instead.
func (*SetScreenResolutionResponse) Descriptor() ([]byte, []int) {
	return file_device_screen_proto_rawDescGZIP(), []int{3}
}

func (x *SetScreenResolutionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_device_screen_proto protoreflect.FileDescriptor

const file_device_screen_proto_rawDesc = "" +
	"\n" +
	"\x13device/screen.proto\x12\x06device\x1a\x1cgoogle/api/annotations.proto\"5\n" +
	"\x17GetScreenCaptureRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"o\n" +
	"\x18GetScreenCaptureResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"f\n" +
	"\x1aSetScreenResolutionRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"7\n" +
	"\x1bSetScreenResolutionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8b\x02\n" +
	"\rDeviceService\x12p\n" +
	"\x10GetScreenCapture\x12\x1f.device.GetScreenCaptureRequest\x1a .device.GetScreenCaptureResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/device/screen\x12\x87\x01\n" +
	"\x13SetScreenResolution\x12\".device.SetScreenResolutionRequest\x1a#.device.SetScreenResolutionResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/device/screen/resolutionB\x1eZ\x1csmart-monitor/pbtypes/deviceb\x06proto3"

var (
	file_device_screen_proto_rawDescOnce sync.Once
	file_device_screen_proto_rawDescData []byte
)

func file_device_screen_proto_rawDescGZIP() []byte {
	file_device_screen_proto_rawDescOnce.Do(func() {
		file_device_screen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_screen_proto_rawDesc), len(file_device_screen_proto_rawDesc)))
	})
	return file_device_screen_proto_rawDescData
}

var file_device_screen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_device_screen_proto_goTypes = []any{
	(*GetScreenCaptureRequest)(nil),     // 0: device.GetScreenCaptureRequest
	(*GetScreenCaptureResponse)(nil),    // 1: device.GetScreenCaptureResponse
	(*SetScreenResolutionRequest)(nil),  // 2: device.SetScreenResolutionRequest
	(*SetScreenResolutionResponse)(nil), // 3: device.SetScreenResolutionResponse
}
var file_device_screen_proto_depIdxs = []int32{
	0, // 0: device.DeviceService.GetScreenCapture:input_type -> device.GetScreenCaptureRequest
	2, // 1: device.DeviceService.SetScreenResolution:input_type -> device.SetScreenResolutionRequest
	1, // 2: device.DeviceService.GetScreenCapture:output_type -> device.GetScreenCaptureResponse
	3, // 3: device.DeviceService.SetScreenResolution:output_type -> device.SetScreenResolutionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_device_screen_proto_init() }
func file_device_screen_proto_init() {
	if File_device_screen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_screen_proto_rawDesc), len(file_device_screen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_screen_proto_goTypes,
		DependencyIndexes: file_device_screen_proto_depIdxs,
		MessageInfos:      file_device_screen_proto_msgTypes,
	}.Build()
	File_device_screen_proto = out.File
	file_device_screen_proto_goTypes = nil
	file_device_screen_proto_depIdxs = nil
}
