// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: system/system.proto

package system

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_system_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{0}
}

func (x *GetSystemInfoRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetSystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Uptime        int32                  `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	KernelVersion string                 `protobuf:"bytes,4,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_system_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{1}
}

func (x *GetSystemInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GetSystemInfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *GetSystemInfoResponse) GetUptime() int32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *GetSystemInfoResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *GetSystemInfoResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_system_system_proto protoreflect.FileDescriptor

const file_system_system_proto_rawDesc = "" +
	"\n" +
	"\x13system/system.proto\x12\x06system\x1a\x1cgoogle/api/annotations.proto\"2\n" +
	"\x14GetSystemInfoRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\x98\x01\n" +
	"\x15GetSystemInfoResponse\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x05R\x06uptime\x12%\n" +
	"\x0ekernel_version\x18\x04 \x01(\tR\rkernelVersion\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp2v\n" +
	"\rSystemService\x12e\n" +
	"\rGetSystemInfo\x12\x1c.system.GetSystemInfoRequest\x1a\x1d.system.GetSystemInfoResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/system/infoB\x1eZ\x1csmart-monitor/pbtypes/systemb\x06proto3"

var (
	file_system_system_proto_rawDescOnce sync.Once
	file_system_system_proto_rawDescData []byte
)

func file_system_system_proto_rawDescGZIP() []byte {
	file_system_system_proto_rawDescOnce.Do(func() {
		file_system_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_system_proto_rawDesc), len(file_system_system_proto_rawDesc)))
	})
	return file_system_system_proto_rawDescData
}

var file_system_system_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_system_system_proto_goTypes = []any{
	(*GetSystemInfoRequest)(nil),  // 0: system.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil), // 1: system.GetSystemInfoResponse
}
var file_system_system_proto_depIdxs = []int32{
	0, // 0: system.SystemService.GetSystemInfo:input_type -> system.GetSystemInfoRequest
	1, // 1: system.SystemService.GetSystemInfo:output_type -> system.GetSystemInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_system_system_proto_init() }
func file_system_system_proto_init() {
	if File_system_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_system_proto_rawDesc), len(file_system_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_system_proto_goTypes,
		DependencyIndexes: file_system_system_proto_depIdxs,
		MessageInfos:      file_system_system_proto_msgTypes,
	}.Build()
	File_system_system_proto = out.File
	file_system_system_proto_goTypes = nil
	file_system_system_proto_depIdxs = nil
}
