// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: disk/disk.proto

package disk

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDiskStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskStatsRequest) Reset() {
	*x = GetDiskStatsRequest{}
	mi := &file_disk_disk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskStatsRequest) ProtoMessage() {}

func (x *GetDiskStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_disk_disk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDiskStatsRequest) Descriptor() ([]byte, []int) {
	return file_disk_disk_proto_rawDescGZIP(), []int{0}
}

func (x *GetDiskStatsRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetDiskStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*DiskPartition       `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskStatsResponse) Reset() {
	*x = GetDiskStatsResponse{}
	mi := &file_disk_disk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskStatsResponse) ProtoMessage() {}

func (x *GetDiskStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_disk_disk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDiskStatsResponse) Descriptor() ([]byte, []int) {
	return file_disk_disk_proto_rawDescGZIP(), []int{1}
}

func (x *GetDiskStatsResponse) GetPartitions() []*DiskPartition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *GetDiskStatsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DiskPartition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	Used          float64                `protobuf:"fixed64,3,opt,name=used,proto3" json:"used,omitempty"`
	Free          float64                `protobuf:"fixed64,4,opt,name=free,proto3" json:"free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskPartition) Reset() {
	*x = DiskPartition{}
	mi := &file_disk_disk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskPartition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskPartition) ProtoMessage() {}

func (x *DiskPartition) ProtoReflect() protoreflect.Message {
	mi := &file_disk_disk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskPartition.ProtoReflect.Descriptor instead.
func (*DiskPartition) Descriptor() ([]byte, []int) {
	return file_disk_disk_proto_rawDescGZIP(), []int{2}
}

func (x *DiskPartition) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskPartition) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiskPartition) GetUsed() float64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *DiskPartition) GetFree() float64 {
	if x != nil {
		return x.Free
	}
	return 0
}

var File_disk_disk_proto protoreflect.FileDescriptor

const file_disk_disk_proto_rawDesc = "" +
	"\n" +
	"\x0fdisk/disk.proto\x12\x04disk\x1a\x1cgoogle/api/annotations.proto\"1\n" +
	"\x13GetDiskStatsRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"i\n" +
	"\x14GetDiskStatsResponse\x123\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x13.disk.DiskPartitionR\n" +
	"partitions\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"n\n" +
	"\rDiskPartition\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x01R\x04used\x12\x12\n" +
	"\x04free\x18\x04 \x01(\x01R\x04free2l\n" +
	"\vDiskService\x12]\n" +
	"\fGetDiskStats\x12\x19.disk.GetDiskStatsRequest\x1a\x1a.disk.GetDiskStatsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/disk/statsB\x1cZ\x1asmart-monitor/pbtypes/diskb\x06proto3"

var (
	file_disk_disk_proto_rawDescOnce sync.Once
	file_disk_disk_proto_rawDescData []byte
)

func file_disk_disk_proto_rawDescGZIP() []byte {
	file_disk_disk_proto_rawDescOnce.Do(func() {
		file_disk_disk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_disk_disk_proto_rawDesc), len(file_disk_disk_proto_rawDesc)))
	})
	return file_disk_disk_proto_rawDescData
}

var file_disk_disk_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_disk_disk_proto_goTypes = []any{
	(*GetDiskStatsRequest)(nil),  // 0: disk.GetDiskStatsRequest
	(*GetDiskStatsResponse)(nil), // 1: disk.GetDiskStatsResponse
	(*DiskPartition)(nil),        // 2: disk.DiskPartition
}
var file_disk_disk_proto_depIdxs = []int32{
	2, // 0: disk.GetDiskStatsResponse.partitions:type_name -> disk.DiskPartition
	0, // 1: disk.DiskService.GetDiskStats:input_type -> disk.GetDiskStatsRequest
	1, // 2: disk.DiskService.GetDiskStats:output_type -> disk.GetDiskStatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_disk_disk_proto_init() }
func file_disk_disk_proto_init() {
	if File_disk_disk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_disk_disk_proto_rawDesc), len(file_disk_disk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_disk_disk_proto_goTypes,
		DependencyIndexes: file_disk_disk_proto_depIdxs,
		MessageInfos:      file_disk_disk_proto_msgTypes,
	}.Build()
	File_disk_disk_proto = out.File
	file_disk_disk_proto_goTypes = nil
	file_disk_disk_proto_depIdxs = nil
}
