// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: security/security.proto

package security

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecurityStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecurityStatusRequest) Reset() {
	*x = GetSecurityStatusRequest{}
	mi := &file_security_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecurityStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecurityStatusRequest) ProtoMessage() {}

func (x *GetSecurityStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecurityStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSecurityStatusRequest) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecurityStatusRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetSecurityStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*SecurityIssue       `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecurityStatusResponse) Reset() {
	*x = GetSecurityStatusResponse{}
	mi := &file_security_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecurityStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecurityStatusResponse) ProtoMessage() {}

func (x *GetSecurityStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecurityStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSecurityStatusResponse) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecurityStatusResponse) GetIssues() []*SecurityIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *GetSecurityStatusResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SecurityIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityIssue) Reset() {
	*x = SecurityIssue{}
	mi := &file_security_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityIssue) ProtoMessage() {}

func (x *SecurityIssue) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityIssue.ProtoReflect.Descriptor instead.
func (*SecurityIssue) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{2}
}

func (x *SecurityIssue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecurityIssue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecurityIssue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

var File_security_security_proto protoreflect.FileDescriptor

const file_security_security_proto_rawDesc = "" +
	"\n" +
	"\x17security/security.proto\x12\bsecurity\x1a\x1cgoogle/api/annotations.proto\"6\n" +
	"\x18GetSecurityStatusRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"j\n" +
	"\x19GetSecurityStatusResponse\x12/\n" +
	"\x06issues\x18\x01 \x03(\v2\x17.security.SecurityIssueR\x06issues\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"]\n" +
	"\rSecurityIssue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity2\x8c\x01\n" +
	"\x0fSecurityService\x12y\n" +
	"\x11GetSecurityStatus\x12\".security.GetSecurityStatusRequest\x1a#.security.GetSecurityStatusResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/security/statusB Z\x1esmart-monitor/pbtypes/securityb\x06proto3"

var (
	file_security_security_proto_rawDescOnce sync.Once
	file_security_security_proto_rawDescData []byte
)

func file_security_security_proto_rawDescGZIP() []byte {
	file_security_security_proto_rawDescOnce.Do(func() {
		file_security_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_security_proto_rawDesc), len(file_security_security_proto_rawDesc)))
	})
	return file_security_security_proto_rawDescData
}

var file_security_security_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_security_security_proto_goTypes = []any{
	(*GetSecurityStatusRequest)(nil),  // 0: security.GetSecurityStatusRequest
	(*GetSecurityStatusResponse)(nil), // 1: security.GetSecurityStatusResponse
	(*SecurityIssue)(nil),             // 2: security.SecurityIssue
}
var file_security_security_proto_depIdxs = []int32{
	2, // 0: security.GetSecurityStatusResponse.issues:type_name -> security.SecurityIssue
	0, // 1: security.SecurityService.GetSecurityStatus:input_type -> security.GetSecurityStatusRequest
	1, // 2: security.SecurityService.GetSecurityStatus:output_type -> security.GetSecurityStatusResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_security_security_proto_init() }
func file_security_security_proto_init() {
	if File_security_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_security_proto_rawDesc), len(file_security_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_security_security_proto_goTypes,
		DependencyIndexes: file_security_security_proto_depIdxs,
		MessageInfos:      file_security_security_proto_msgTypes,
	}.Build()
	File_security_security_proto = out.File
	file_security_security_proto_goTypes = nil
	file_security_security_proto_depIdxs = nil
}
