// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: Infrastructure/resources/resource.proto

package resources

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourcesRequest) Reset() {
	*x = GetResourcesRequest{}
	mi := &file_Infrastructure_resources_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourcesRequest) ProtoMessage() {}

func (x *GetResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_resources_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourcesRequest.ProtoReflect.Descriptor instead.
func (*GetResourcesRequest) Descriptor() ([]byte, []int) {
	return file_Infrastructure_resources_resource_proto_rawDescGZIP(), []int{0}
}

func (x *GetResourcesRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourcesResponse) Reset() {
	*x = GetResourcesResponse{}
	mi := &file_Infrastructure_resources_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourcesResponse) ProtoMessage() {}

func (x *GetResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_resources_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourcesResponse.ProtoReflect.Descriptor instead.
func (*GetResourcesResponse) Descriptor() ([]byte, []int) {
	return file_Infrastructure_resources_resource_proto_rawDescGZIP(), []int{1}
}

func (x *GetResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *GetResourcesResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_Infrastructure_resources_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_Infrastructure_resources_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_Infrastructure_resources_resource_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_Infrastructure_resources_resource_proto protoreflect.FileDescriptor

const file_Infrastructure_resources_resource_proto_rawDesc = "" +
	"\n" +
	"'Infrastructure/resources/resource.proto\x12\tresources\x1a\x1cgoogle/api/annotations.proto\"1\n" +
	"\x13GetResourcesRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"g\n" +
	"\x14GetResourcesResponse\x121\n" +
	"\tresources\x18\x01 \x03(\v2\x13.resources.ResourceR\tresources\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"D\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value2y\n" +
	"\x0fResourceService\x12f\n" +
	"\fGetResources\x12\x1e.resources.GetResourcesRequest\x1a\x1f.resources.GetResourcesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/resourcesB0Z.smart-monitor/pbtypes/Infrastructure/resourcesb\x06proto3"

var (
	file_Infrastructure_resources_resource_proto_rawDescOnce sync.Once
	file_Infrastructure_resources_resource_proto_rawDescData []byte
)

func file_Infrastructure_resources_resource_proto_rawDescGZIP() []byte {
	file_Infrastructure_resources_resource_proto_rawDescOnce.Do(func() {
		file_Infrastructure_resources_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Infrastructure_resources_resource_proto_rawDesc), len(file_Infrastructure_resources_resource_proto_rawDesc)))
	})
	return file_Infrastructure_resources_resource_proto_rawDescData
}

var file_Infrastructure_resources_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Infrastructure_resources_resource_proto_goTypes = []any{
	(*GetResourcesRequest)(nil),  // 0: resources.GetResourcesRequest
	(*GetResourcesResponse)(nil), // 1: resources.GetResourcesResponse
	(*Resource)(nil),             // 2: resources.Resource
}
var file_Infrastructure_resources_resource_proto_depIdxs = []int32{
	2, // 0: resources.GetResourcesResponse.resources:type_name -> resources.Resource
	0, // 1: resources.ResourceService.GetResources:input_type -> resources.GetResourcesRequest
	1, // 2: resources.ResourceService.GetResources:output_type -> resources.GetResourcesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Infrastructure_resources_resource_proto_init() }
func file_Infrastructure_resources_resource_proto_init() {
	if File_Infrastructure_resources_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Infrastructure_resources_resource_proto_rawDesc), len(file_Infrastructure_resources_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Infrastructure_resources_resource_proto_goTypes,
		DependencyIndexes: file_Infrastructure_resources_resource_proto_depIdxs,
		MessageInfos:      file_Infrastructure_resources_resource_proto_msgTypes,
	}.Build()
	File_Infrastructure_resources_resource_proto = out.File
	file_Infrastructure_resources_resource_proto_goTypes = nil
	file_Infrastructure_resources_resource_proto_depIdxs = nil
}
